### PR TITLE
v1.1.0

### PR DESCRIPTION
**Pull request by gmpassos**
- Added a working example.
- Null safety fixes.
- Added Dart CI.

- Dart format (needed for pub.dev).

- sdk: '>=2.18.0 <3.0.0'
- collection: ^1.16.0
- dependency_validator: ^3.2.2
- dio_logger: ^4.0.8+8
- image: ^3.3.0
- json_annotation: ^4.7.0
- meta: ^1.8.0
- path: ^1.8.3
- uuid: ^3.0.7
- build_runner: ^2.3.3
- json_serializable: ^6.5.4
- lints: ^2.0.1
- test: ^1.22.2

### CODE REVIEW

**Comment by gmpassos** [comment]
I think that this version can be published to [pub.dev](https://pub.dev)

I you want I can help to improve this Dart package.

Best regards.

**Review by Nerixyz — CHANGES_REQUESTED** [review]
Small nitpick.

**Comment by Nerixyz** [comment]
> I you want I can help to improve this Dart package.

I'd be okay if you take this project (if you want), since I no longer maintain/use it.

**Comment by gmpassos** [comment]
Well I can take this project, since I will use it in a long-term project.

How should we proceed to publish on pub.dev?

**Comment by gmpassos** [comment]
https://stackoverflow.com/questions/20786435/transferring-a-dart-library-to-another-owner-in-pub-dartlang-org

**Comment by gmpassos** [comment]
If you transfer this project I will continue from my fork

**Comment by gmpassos** [comment]
I have approved all your suggestions.

**Review by Nerixyz — APPROVED** [review]

**Comment by Nerixyz** [comment]
> https://stackoverflow.com/questions/20786435/transferring-a-dart-library-to-another-owner-in-pub-dartlang-org

I don't think I'm the uploader on pub.dev. At least, I can't access the package with my account. Thus, I can only transfer this project on GitHub.

**Comment by Nerixyz** [comment]
I can't transfer this repo right now, you need to delete your fork first:
> gmpassos/instagram_private_api already exists

**Comment by gmpassos** [comment]
deleted

**Comment by Nerixyz** [comment]
I sent you the request.

**Comment by gmpassos** [comment]
@Nerixyz  accepted

**Comment by gmpassos** [comment]
@Nerixyz do you know how to proceed with pub.dev ownership? I don't want to publish it with a different name.

Best regards

**Comment by Nerixyz** [comment]
> @Nerixyz do you know how to proceed with pub.dev ownership? I don't want to publish it with a different name.
> 
> Best regards

As I said, I can't access the pub.dev package, so I can't transfer ownership. You will have to advise users to use this as a git dependency (basically what's in the current readme).

**Comment by gmpassos** [comment]
Do you know the owner of the pub.dev account?

**Pull request merged**
